import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body className="w-full max-w-screen-xl mx-auto">
        <header className="sticky bg-white z-10 border-b">
          <Navbar />
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
