import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import AuthContext from "./context/AuthContext";
import SWRconfigContext from "./context/SWRconfigContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body className="w-full max-w-screen-xl mx-auto">
        <AuthContext>
          <header className="sticky bg-white z-10 border-b">
            <Navbar />
          </header>
          <main className="w-full flex justify-center bg-neutral-100 min-h-full">
            <SWRconfigContext>{children}</SWRconfigContext>
          </main>
        </AuthContext>
      </body>
    </html>
  );
}
